const arts = [
    {
        title: 'Wheat Field with Cypresses',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT1567.jpg',
        artist: 'Vincent van Gogh',
        artistBio: 'Dutch, Zundert 1853–1890 Auvers-sur-Oise',
        dateCreated: '1889',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Landscapes' ]
    },
    {
        title: 'Madame Roulin and Her Baby',
        img: 'https://images.metmuseum.org/CRDImages/rl/web-large/DT3154.jpg',
        artist: 'Vincent van Gogh',
        artistBio: 'Dutch, Zundert 1853–1890 Auvers-sur-Oise',
        dateCreated: '1888',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Infants' ]
    },
    {
        title: 'Road in Etten',
        img: 'https://images.metmuseum.org/CRDImages/rl/web-large/DP359031.jpg',
        artist: 'Vincent van Gogh',
        artistBio: 'Dutch, Zundert 1853–1890 Auvers-sur-Oise',
        dateCreated: '1881',
        description: 'Chalk, pencil, pastel, watercolor.  Underdrawing in pen and brown ink.',
        category: 'Drawing',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Roads' ]
    },
    {
        title: 'Corridor in the Asylum',
        img: 'https://images.metmuseum.org/CRDImages/dp/web-large/DT365509.jpg',
        artist: 'Vincent van Gogh',
        artistBio: 'Dutch, Zundert 1853–1890 Auvers-sur-Oise',
        dateCreated: 'September 1889',
        description: 'Oil color and essence over black chalk on pink laid ("Ingres") paper',
        category: 'Drawing',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Hospitals' ]
    },
    {
        title: 'Madame Georges Charpentier (Marguérite-Louise Lemonnier, 1848–1904) and Her Children, Georgette-Berthe (1872–1945) and Paul-Émile-Charles (1875–1895)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT49.jpg',
        artist: 'Auguste Renoir',
        artistBio: 'French, Limoges 1841–1919 Cagnes-sur-Mer',
        dateCreated: '1878',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Interiors' ]
    },
    {
        title: 'Two Young Girls at the Piano',
        img: 'https://images.metmuseum.org/CRDImages/rl/web-large/DT3131.jpg',
        artist: 'Auguste Renoir',
        artistBio: 'French, Limoges 1841–1919 Cagnes-sur-Mer',
        dateCreated: '1892',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Girls' ]
    },
    {
        title: 'Madonna and Child Enthroned with Saints',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT13.jpg',
        artist: 'Raphael (Raffaello Sanzio or Santi)',
        artistBio: 'Italian, Urbino 1483–1520 Rome',
        dateCreated: 'ca. 1504',
        description: 'Oil and gold on wood',
        category: 'Painting, altarpiece',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Angels' ]
    },  
    {
        title: 'Merry Company on a Terrace',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP146455.jpg',
        artist: 'Jan Steen',
        artistBio: 'Dutch, Leiden 1626–1679 Leiden',
        dateCreated: 'ca. 1670',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Food' ]
    },
    {
        title: 'Manuel Osorio Manrique de Zuñiga (1784–1792)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP287624.jpg',
        artist: 'Goya (Francisco de Goya y Lucientes)',
        artistBio: 'Spanish, Fuendetodos 1746–1828 Bordeaux',
        dateCreated: '1787–88',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Birds' ]
    },
    {
        title: 'Study of a Young Woman',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP353256.jpg',
        artist: 'Johannes Vermeer',
        artistBio: 'Dutch, Delft 1632–1675 Delft',
        dateCreated: 'ca. 1665–67',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Portraits' ]
    },
    {
        title: 'Juan de Pareja (ca. 1608–1670)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-14286-001.jpg',
        artist: 'Velázquez (Diego Rodríguez de Silva y Velázquez)',
        artistBio: 'Spanish, Seville 1599–1660 Madrid',
        dateCreated: '1650',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'The Adoration of the Shepherds',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP213831.jpg',
        artist: 'Andrea Mantegna',
        artistBio: 'Italian, Isola di Carturo 1430/31–1506 Mantua',
        dateCreated: 'shortly after 1450',
        description: 'Tempera on canvas, transferred from wood',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Adoration of the Shepherds' ]
    },
    {
        title: 'Aristotle with a Bust of Homer',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP319026.jpg',
        artist: 'Rembrandt (Rembrandt van Rijn)',
        artistBio: 'Dutch, Leiden 1606–1669 Amsterdam',
        dateCreated: '1653',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'Clothing the Naked',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-15762-001.jpg',
        artist: 'Michiel Sweerts',
        artistBio: 'Flemish, Brussels 1618–1664 Goa',
        dateCreated: 'ca. 1661',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'Lucas van Uffel (died 1637)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT31.jpg',
        artist: 'Anthony van Dyck',
        artistBio: 'Flemish, Antwerp 1599–1641 London',
        dateCreated: 'ca. 1622',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Musical Instruments' ]
    },
    {
        title: 'Blind Orion Searching for the Rising Sun',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP148490.jpg',
        artist: 'Nicolas Poussin',
        artistBio: 'French, Les Andelys 1594–1665 Rome',
        dateCreated: '1658',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Orion' ]
    },
    {
        title: 'Allegory of the Planets and Continents',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-14286-007.jpg',
        artist: 'Giovanni Battista Tiepolo',
        artistBio: 'Italian, Venice 1696–1770 Madrid',
        dateCreated: '1752',
        description: 'Oil on canvas',
        category: 'Painting, sketch',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'The Immaculate Conception',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT1138.jpg',
        artist: 'Guido Reni',
        artistBio: 'Italian, Bologna 1575–1642 Bologna',
        dateCreated: '1627',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Angels' ]
    },
    {
        title: 'Bridge over a Pond of Water Lilies',
        img: 'https://collectionapi.metmuseum.org/api/collection/v1/iiif/437127/796089/restricted',
        artist: 'Claude Monet',
        artistBio: 'French, Paris 1840–1926 Giverny',
        dateCreated: '1899',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Bridges' ]
    },
    {
        title: 'The Coronation of the Virgin',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT11343.jpg',
        artist: 'Annibale Carracci',
        artistBio: 'Italian, Bologna 1560–1609 Rome',
        dateCreated: 'after 1595',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Virgin Mary' ]
    },
    {
        title: 'The Triumph of Fame; (reverse) Impresa of the Medici Family and Arms of the Medici and Tornabuoni Families',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP164870.jpg',
        artist: 'Giovanni di ser Giovanni Guidi (called Scheggia)',
        artistBio: 'Italian, San Giovanni Valdarno 1406–1486 Florence',
        dateCreated: 'ca. 1449',
        description: 'Tempera, silver, and gold on wood',
        category: 'Painting, birth tray',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Armor' ]
    },
    {
        title: 'The Card Players',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP231550.jpg',
        artist: 'Paul Cézanne',
        artistBio: 'French, Aix-en-Provence 1839–1906 Aix-en-Provence',
        dateCreated: '1890–92',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'Saint Andrew',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP343101.jpg',
        artist: 'Simone Martini',
        artistBio: 'Italian, Siena, active by 1315–died 1344 Avignon',
        dateCreated: 'ca. 1326',
        description: 'Tempera on wood, gold ground',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'Queen Henrietta Maria',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-18371-001.jpg',
        artist: 'Anthony van Dyck',
        artistBio: 'Flemish, Antwerp 1599–1641 London',
        dateCreated: '1636',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Queens' ]
    },
    {
        title: 'Sibylle',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-16592-001.jpg',
        artist: 'Camille Corot',
        artistBio: 'French, Paris 1796–1875 Paris',
        dateCreated: 'ca. 1870',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Women' ]
    },
    {
        title: 'Mars and Venus United by Love',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP167124.jpg',
        artist: 'Paolo Veronese (Paolo Caliari)',
        artistBio: 'Italian, Verona 1528–1588 Venice',
        dateCreated: '1570s',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Cupid' ]
    },
    {
        title: 'Joseph-Antoine Moltedo (born 1775)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP151185.jpg',
        artist: 'Jean Auguste Dominique Ingres',
        artistBio: 'French, Montauban 1780–1867 Paris',
        dateCreated: 'ca. 1810',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'The Third-Class Carriage',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-21027-001.jpg',
        artist: 'Honoré Daumier',
        artistBio: 'French, Marseilles 1808–1879 Valmondois',
        dateCreated: 'ca. 1862–64',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Nursing' ]
    },
    {
        title: 'Woman Having Her Hair Combed',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP253480.jpg',
        artist: 'Edgar Degas',
        artistBio: 'French, Paris 1834–1917 Paris',
        dateCreated: 'ca. 1886–88',
        description: 'Pastel on light green wove paper, now discolored to warm gray, affixed to original pulpboard mount',
        category: 'Drawing',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Women' ]
    },
    {
        title: 'By the Seashore',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-14936-039.jpg',
        artist: 'Auguste Renoir',
        artistBio: 'French, Limoges 1841–1919 Cagnes-sur-Mer',
        dateCreated: '1883',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Portraits' ]
    },
    {
        title: 'Study for "A Sunday on La Grande Jatte"',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP259921.jpg',
        artist: 'Georges Seurat',
        artistBio: 'French, Paris 1859–1891 Paris',
        dateCreated: '1884',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Leisure' ]
    },
    {
        title: 'The Repast of the Lion',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT50.jpg',
        artist: 'Henri Rousseau (le Douanier)',
        artistBio: 'French, Laval 1844–1910 Paris',
        dateCreated: 'ca. 1907',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Forests' ]
    },
    {
        title: 'Soap Bubbles',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP356133.jpg',
        artist: 'Jean Siméon Chardin',
        artistBio: 'French, Paris 1699–1779 Paris',
        dateCreated: 'ca. 1733–34',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Boys' ]
    },
    {
        title: 'Woman with a Parrot',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-17680-001.jpg',
        artist: 'Gustave Courbet',
        artistBio: 'French, Ornans 1819–1877 La Tour-de-Peilz',
        dateCreated: '1866',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Female Nudes' ]
    },
    {
        title: 'The Adoration of the Magi',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-19501-001.jpg',
        artist: 'Giotto di Bondone',
        artistBio: 'Italian, Florentine, 1266/76–1337',
        dateCreated: 'possibly ca. 1320',
        description: 'Tempera on wood, gold ground',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Angels' ]
    },
    {
        title: 'Portrait of a Young Man',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-14286-011.jpg',
        artist: 'Bronzino (Agnolo di Cosimo di Mariano)',
        artistBio: 'Italian, Monticelli 1503–1572 Florence',
        dateCreated: '1530s',
        description: 'Oil on wood',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'Hermann von Wedigh III (died 1560)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP164836.jpg',
        artist: 'Hans Holbein the Younger',
        artistBio: 'German, Augsburg 1497/98–1543 London',
        dateCreated: '1532',
        description: 'Oil and gold on oak',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'The Crucifixion with Saints and a Donor',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT1467.jpg',
        artist: 'Joos van Cleve',
        artistBio: 'Netherlandish, Cleve ca. 1485–1540/41 Antwerp',
        dateCreated: 'ca. 1520',
        description: 'Oil on wood',
        category: 'Painting, triptych',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Christ' ]
    },
    {
        title: 'A Woman Seated beside a Vase of Flowers (Madame Paul Valpinçon?)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-25460-001.jpg',
        artist: 'Edgar Degas',
        artistBio: 'French, Paris 1834–1917 Paris',
        dateCreated: '1865',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Pitchers' ]
    },
    {
        title: 'Boating',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-25466-001.jpg',
        artist: 'Edouard Manet',
        artistBio: 'French, Paris 1832–1883 Paris',
        dateCreated: '1874',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'Mezzetin',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP170811.jpg',
        artist: 'Antoine Watteau',
        artistBio: 'French, Valenciennes 1684–1721 Nogent-sur-Marne',
        dateCreated: 'ca. 1718–20',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'The Holy Family with Saints Anne and Catherine of Alexandria',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT16.jpg',
        artist: 'Jusepe de Ribera (called Lo Spagnoletto)',
        artistBio: 'Spanish, Játiva 1591–1652 Naples',
        dateCreated: '1648',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Virgin Mary' ]
    },
    {
        title: "Francesco d'Este (born about 1429, died after July 20, 1486)",
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-26278-001.jpg',
        artist: 'Rogier van der Weyden',
        artistBio: 'Netherlandish, Tournai ca. 1399–1464 Brussels',
        dateCreated: 'ca. 1460',
        description: 'Oil on wood',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Rings' ]
    },
    {
        title: 'The Rest on the Flight into Egypt',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-14936-023.jpg',
        artist: 'Gerard David',
        artistBio: 'Netherlandish, Oudewater ca. 1455–1523 Bruges',
        dateCreated: 'ca. 1512–15',
        description: 'Oil on wood',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Virgin Mary' ]
    },
    {
        title: 'The Abduction of the Sabine Women',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-14286-013.jpg',
        artist: 'Nicolas Poussin',
        artistBio: 'French, Les Andelys 1594–1665 Rome',
        dateCreated: 'probably 1633–34',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Suffering' ]
    },
    {
        title: 'Portrait of a Carthusian',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT26.jpg',
        artist: 'Petrus Christus',
        artistBio: 'Netherlandish, Baarle-Hertog (Baerle-Duc), active by 1444–died 1475/76 Bruges',
        dateCreated: '1446',
        description: 'Oil on wood',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'Venus and Adonis',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-19299-001.jpg',
        artist: 'Titian (Tiziano Vecellio)',
        artistBio: 'Italian, Pieve di Cadore ca. 1485/90?–1576 Venice',
        dateCreated: '1550s',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Cupid' ]
    },
    {
        title: 'The Penitent Magdalen',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT7252.jpg',
        artist: 'Georges de La Tour',
        artistBio: 'French, Vic-sur-Seille 1593–1652 Lunéville',
        dateCreated: 'ca. 1640',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Skulls' ]
    },
    {
        title: 'Self-Portrait with a Straw Hat (obverse: The Potato Peeler)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT1502_cropped2.jpg',
        artist: 'Vincent van Gogh',
        artistBio: 'Dutch, Zundert 1853–1890 Auvers-sur-Oise',
        dateCreated: '1887',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'Portrait of a Woman with a Man at a Casement',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP159891.jpg',
        artist: 'Fra Filippo Lippi',
        artistBio: 'Italian, Florence ca. 1406–1469 Spoleto',
        dateCreated: 'ca. 1440',
        description: 'Tempera on wood',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'The Annunciation',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP240360.jpg',
        artist: 'Hans Memling',
        artistBio: 'Netherlandish, Seligenstadt, active by 1465–died 1494 Bruges',
        dateCreated: 'ca. 1465–70',
        description: 'Oil on wood',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Virgin Mary' ]
    },
    {
        title: 'Madonna and Child',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP243637.jpg',
        artist: 'Filippino Lippi',
        artistBio: 'Italian, Prato ca. 1457–1504 Florence',
        dateCreated: 'ca. 1483–84',
        description: 'Tempera, oil, and gold on wood',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Madonna and Child' ]
    },
    {
        title: 'The Holy Family with the Young Saint John the Baptist',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP295025.jpg',
        artist: "Andrea del Sarto (Andrea d'Agnolo)",
        artistBio: 'Italian, Florence 1486–1530 Florence',
        dateCreated: 'ca. 1528',
        description: 'Oil on wood',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Virgin Mary' ]
    },
    {
        title: 'Young Woman Seated on a Sofa',
        img: 'https://collectionapi.metmuseum.org/api/collection/v1/iiif/437160/794820/restricted',
        artist: 'Berthe Morisot',
        artistBio: 'French, Bourges 1841–1895 Paris',
        dateCreated: 'ca. 1879',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Portraits' ]
    },
    {
        title: 'The Last Communion of Saint Jerome',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-24049-001.jpg',
        artist: 'Botticelli (Alessandro di Mariano Filipepi)',
        artistBio: 'Italian, Florence 1444/45–1510 Florence',
        dateCreated: 'early 1490s',
        description: 'Tempera and gold on wood',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Saint Jerome' ]
    },
    {
        title: 'The Dream of the Shepherd (Der Traum des Hirten)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP318843.jpg',
        artist: 'Ferdinand Hodler',
        artistBio: 'Swiss, Bern 1853–1918 Geneva',
        dateCreated: '1896',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Female Nudes' ]
    },
    {
        title: 'The Young Virgin',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT17.jpg',
        artist: 'Francisco de Zurbarán',
        artistBio: 'Spanish, Fuente de Cantos 1598–1664 Madrid',
        dateCreated: 'ca. 1632–33',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Lilies' ]
    },
    {
        title: 'Inferno',
        img: 'https://collectionapi.metmuseum.org/api/collection/v1/iiif/749639/1705702/restricted',
        artist: 'Franz von Stuck',
        artistBio: 'German, Tettenweis 1863–1928 Munich',
        dateCreated: '1908',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Male Nudes' ]
    },
    {
        title: 'The Dance Class',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-20101-001.jpg',
        artist: 'Edgar Degas',
        artistBio: 'French, Paris 1834–1917 Paris',
        dateCreated: '1874',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Girls' ]
    },
    {
        title: 'Whalers',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-13360-001.jpg',
        artist: 'Joseph Mallord William Turner',
        artistBio: 'British, London 1775–1851 London',
        dateCreated: 'ca. 1845',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Whales' ]
    },
    {
        title: 'Two Men Contemplating the Moon',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT4626.jpg',
        artist: 'Caspar David Friedrich',
        artistBio: 'German, Greifswald 1774–1840 Dresden',
        dateCreated: 'ca. 1825–30',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Contemplation' ]
    },
    {
        title: 'Still Life with Apples and a Pot of Primroses',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT47.jpg',
        artist: 'Paul Cézanne',
        artistBio: 'French, Aix-en-Provence 1839–1906 Aix-en-Provence',
        dateCreated: 'ca. 1890',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Apples' ]
    },
    {
        title: 'Garden at Sainte-Adresse',
        img: 'https://collectionapi.metmuseum.org/api/collection/v1/iiif/437133/1566072/restricted',
        artist: 'Claude Monet',
        artistBio: 'French, Paris 1840–1926 Giverny',
        dateCreated: '1867',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Gardens' ]
    },
    {
        title: 'The Abduction of Rebecca',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-14344-001.jpg',
        artist: 'Eugène Delacroix',
        artistBio: 'French, Charenton-Saint-Maurice 1798–1863 Paris',
        dateCreated: '1846',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Battles' ]
    },
    {
        title: 'The Englishman (William Tom Warrener, 1861–1934) at the Moulin Rouge',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT1500.jpg',
        artist: 'Henri de Toulouse-Lautrec',
        artistBio: 'French, Albi 1864–1901 Saint-André-du-Bois',
        dateCreated: '1892',
        description: 'Oil on cardboard',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'Madonna and Child',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT375.jpg',
        artist: 'Giovanni Bellini',
        artistBio: 'Italian, Venice, active by 1459–died 1516 Venice',
        dateCreated: 'late 1480s',
        description: 'Oil on wood',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Infants' ]
    },
    {
        title: 'Mäda Primavesi (1903–2000)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP243354.jpg',
        artist: 'Gustav Klimt',
        artistBio: 'Austrian, Baumgarten 1862–1918 Vienna',
        dateCreated: '1912–13',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Girls' ]
    },
    {
        title: 'Irises',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP346474.jpg',
        artist: 'Vincent van Gogh',
        artistBio: 'Dutch, Zundert 1853–1890 Auvers-sur-Oise',
        dateCreated: '1890',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Still Life' ]
    },
    {
        title: 'Joan of Arc',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-14201-049.jpg',
        artist: 'Jules Bastien-Lepage',
        artistBio: 'French, Damvillers 1848–1884 Paris',
        dateCreated: '1879',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Gardens' ]
    },
    {
        title: 'The Musicians',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-687-001.jpg',
        artist: 'Caravaggio (Michelangelo Merisi)',
        artistBio: 'Italian, Milan or Caravaggio 1571–1610 Porto Ercole',
        dateCreated: '1597',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Grapes' ]
    },
    {
        title: 'The Horse Fair',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-23550-001.jpg',
        artist: 'Rosa Bonheur',
        artistBio: 'French, Bordeaux 1822–1899 Thomery',
        dateCreated: '1852–55',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Paris' ]
    },
    {
        title: 'Cottage Children (The Wood Gatherers)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP169640.jpg',
        artist: 'Thomas Gainsborough',
        artistBio: 'British, Sudbury 1727–1788 London',
        dateCreated: '1787',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Children' ]
    },
    {
        title: 'Captain George K. H. Coussmaker (1759–1801)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP169215.jpg',
        artist: 'Sir Joshua Reynolds',
        artistBio: 'British, Plympton 1723–1792 London',
        dateCreated: '1782',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'Haystacks: Autumn',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP124093.jpg',
        artist: 'Jean-François Millet',
        artistBio: 'French, Gruchy 1814–1875 Barbizon',
        dateCreated: 'ca. 1874',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Autumn' ]
    },
    {
        title: 'Elizabeth Farren (born about 1759, died 1829), Later Countess of Derby',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP169218.jpg',
        artist: 'Sir Thomas Lawrence',
        artistBio: 'British, Bristol 1769–1830 London',
        dateCreated: '1790',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Portraits' ]
    },
    {
        title: 'Ia Orana Maria (Hail Mary)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT1025.jpg',
        artist: 'Paul Gauguin',
        artistBio: 'French, Paris 1848–1903 Atuona, Hiva Oa, Marquesas Islands',
        dateCreated: '1891',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Women' ]
    },
    {
        title: 'Madame Cézanne (Hortense Fiquet, 1850–1922) in a Red Dress',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP320128.jpg',
        artist: 'Paul Cézanne',
        artistBio: 'French, Aix-en-Provence 1839–1906 Aix-en-Provence',
        dateCreated: '1888–90',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Portraits' ]
    },
    {
        title: 'Virgin and Child',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-14936-010.jpg',
        artist: 'Bartolomé Estebán Murillo',
        artistBio: 'Spanish, Seville 1617–1682 Seville',
        dateCreated: '1670s',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Madonna and Child' ]
    },
    {
        title: 'The Fortune-Teller',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-14286-015.jpg',
        artist: 'Georges de La Tour',
        artistBio: 'French, Vic-sur-Seille 1593–1652 Lunéville',
        dateCreated: 'probably 1630s',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'Circus Sideshow (Parade de cirque)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP375450_cropped.jpg',
        artist: 'Georges Seurat',
        artistBio: 'French, Paris 1859–1891 Paris',
        dateCreated: '1887–88',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Musical Instruments' ]
    },
    {
        title: 'The Baptism of Christ',
        img: 'https://collectionapi.metmuseum.org/api/collection/v1/iiif/440393/803222/restricted',
        artist: 'Jacopo Bassano (Jacopo da Ponte)',
        artistBio: 'Italian, Bassano del Grappa ca. 1510–1592 Bassano del Grappa',
        dateCreated: 'ca. 1590',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'The Crucifixion; The Last Judgment',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/LC-33_92ab-Primary_Temp.jpg',
        artist: 'Jan van Eyck',
        artistBio: 'Netherlandish, Maaseik ca. 1390–1441 Bruges',
        dateCreated: 'ca. 1440–41',
        description: 'Oil on canvas, transferred from wood',
        category: 'Painting, diptych',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Angels' ]
    },
    {
        title: 'Samson Captured by the Philistines',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DT503.jpg',
        artist: 'Guercino (Giovanni Francesco Barbieri)',
        artistBio: 'Italian, Cento 1591–1666 Bologna',
        dateCreated: '1619',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Women' ]
    },
    {
        title: 'The Death of Socrates',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-13139-001.jpg',
        artist: 'Jacques Louis David',
        artistBio: 'French, Paris 1748–1825 Brussels',
        dateCreated: '1787',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Lyres' ]
    },
    {
        title: 'The Meditation on the Passion',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP296427.jpg',
        artist: 'Vittore Carpaccio',
        artistBio: 'Italian, Venice 1460/66?–1525/26 Venice',
        dateCreated: 'ca. 1490',
        description: 'Oil and tempera on wood',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Christ' ]
    },
    {
        title: 'The Toilette of Venus',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-411-01.jpg',
        artist: 'François Boucher',
        artistBio: 'French, Paris 1703–1770 Paris',
        dateCreated: '1751',
        description: 'Oil on canvas',
        category: 'Painting, overdoor',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Female Nudes' ]
    },
    {
        title: 'A Woman with a Dog',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-1019-01.jpg',
        artist: 'Jean Honoré Fragonard',
        artistBio: 'French, Grasse 1732–1806 Paris',
        dateCreated: 'ca. 1769',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Portraits' ]
    },
    {
        title: 'The Love Song',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP323394.jpg',
        artist: 'Sir Edward Burne-Jones',
        artistBio: 'British, Birmingham 1833–1898 Fulham',
        dateCreated: '1868–77',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Musical Instruments' ]
    },
    {
        title: 'The Forest in Winter at Sunset',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP247630.jpg',
        artist: 'Théodore Rousseau',
        artistBio: 'French, Paris 1812–1867 Barbizon',
        dateCreated: 'ca. 1846–67',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Forests' ]
    },
    {
        title: 'The Trojan Women Setting Fire to Their Fleet',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP226145.jpg',
        artist: 'Claude Lorrain (Claude Gellée)',
        artistBio: 'French, Chamagne 1604/5?–1682 Rome',
        dateCreated: 'ca. 1643',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Aeneid' ]
    },
    {
        title: 'A Bouquet of Flowers',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-19451-001.jpg',
        artist: 'Clara Peeters',
        artistBio: 'Flemish, Mechelen ca. 1587–after 1636 Ghent',
        dateCreated: 'ca. 1612',
        description: 'Oil on wood',
        category: '',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Still Life' ]
    },
    {
        title: 'The Spanish Singer',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/dp130799.jpg',
        artist: 'Edouard Manet',
        artistBio: 'French, Paris 1832–1883 Paris',
        dateCreated: '1860',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Music' ]
    },
    {
        title: 'Saint John on Patmos',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP164867.jpg',
        artist: 'Hans Baldung (called Hans Baldung Grien)',
        artistBio: 'German, Schwäbisch Gmünd (?) 1484/85–1545 Strasbourg',
        dateCreated: 'ca. 1511',
        description: 'Oil, gold, and white metal on spruce',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Eagles' ]
    },
    {
        title: 'The Harvesters',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP119115.jpg',
        artist: 'Pieter Bruegel the Elder',
        artistBio: 'Netherlandish, Breda (?) ca. 1525–1569 Brussels',
        dateCreated: '1565',
        description: 'Oil on wood',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Food' ]
    },
    {
        title: 'The Judgment of Paris',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP280358.jpg',
        artist: 'Lucas Cranach the Elder',
        artistBio: 'German, Kronach 1472–1553 Weimar',
        dateCreated: 'ca. 1528',
        description: 'Oil on beech',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Paris' ]
    },
    {
        title: 'Cardinal Fernando Niño de Guevara (1541–1609)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-17777-001.jpg',
        artist: 'El Greco (Domenikos Theotokopoulos)',
        artistBio: 'Greek, Iráklion (Candia) 1541–1614 Toledo',
        dateCreated: 'ca. 1600',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'Comtesse de la Châtre (Marie Charlotte Louise Perrette Aglaé Bontemps, 1762–1848)',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP320086.jpg',
        artist: 'Elisabeth Louise Vigée Le Brun',
        artistBio: 'French, Paris 1755–1842 Paris',
        dateCreated: '1789',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Portraits' ]
    },
    {
        title: 'View of Toledo',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP349564.jpg',
        artist: 'El Greco (Domenikos Theotokopoulos)',
        artistBio: 'Greek, Iráklion (Candia) 1541–1614 Toledo',
        dateCreated: 'ca. 1599–1600',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Buildings' ]
    },
    {
        title: 'Broken Eggs',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-12952-001.jpg',
        artist: 'Jean-Baptiste Greuze',
        artistBio: 'French, Tournus 1725–1805 Paris',
        dateCreated: '1756',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Interiors' ]
    },
    {
        title: 'The Bodmer Oak, Fontainebleau Forest',
        img: 'https://collectionapi.metmuseum.org/api/collection/v1/iiif/437131/796060/restricted',
        artist: 'Claude Monet',
        artistBio: 'French, Paris 1840–1926 Giverny',
        dateCreated: '1865',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Forests' ]
    },
    {
        title: "The Shepherd's Song",
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-14201-001.jpg',
        artist: 'Pierre Puvis de Chavannes',
        artistBio: 'French, Lyons 1824–1898 Paris',
        dateCreated: '1891',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    },
    {
        title: 'Young Woman with a Water Pitcher',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP353257.jpg',
        artist: 'Johannes Vermeer',
        artistBio: 'Dutch, Delft 1632–1675 Delft',
        dateCreated: 'ca. 1662',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Interiors' ]
    },
    {
        title: 'The Crucifixion with the Virgin and Saint John',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP146490.jpg',
        artist: 'Hendrick ter Brugghen',
        artistBio: 'Dutch, The Hague? 1588–1629 Utrecht',
        dateCreated: 'ca. 1624–25',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Christ' ]
    },
    {
        title: 'Fish Market',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP375107.jpg',
        artist: 'Joachim Beuckelaer',
        artistBio: 'Netherlandish, Antwerp 1533–1575 Antwerp',
        dateCreated: '1568',
        description: 'Oil on Baltic oak',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Food' ]
    },
    {
        title: 'A Hunting Scene',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-19296-001.jpg',
        artist: "Piero di Cosimo (Piero di Lorenzo di Piero d'Antonio)",
        artistBio: 'Italian, Florence 1462–1522 Florence',
        dateCreated: 'ca. 1494–1500',
        description: 'Tempera and oil transferred to Masonite',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Lions' ]
    },
    {
        title: 'Oedipus and the Sphinx',
        img: 'https://images.metmuseum.org/CRDImages/ep/web-large/DP-14201-023.jpg',
        artist: 'Gustave Moreau',
        artistBio: 'French, Paris 1826–1898 Paris',
        dateCreated: '1864',
        description: 'Oil on canvas',
        category: 'Painting',
        museum: 'Metropolitan Museum of Art, New York, NY',
        tags: [ 'Men' ]
    }
]
    
module.exports = arts